"""Built-in colour themes."""

THEMES = {
    'technics-blue': {
        'name': 'Technics Blue',
        'dark': True,
        # UI colours
        'window_bg':    '#0D1A2A',
        'header_bg':    '#091422',
        'card_bg':      '#122030',
        'input_bg':     '#152233',
        'hover_bg':     '#1C2E44',
        'note_bg':      '#0B1620',
        'art_bg':       '#0A1525',
        'fg':           '#EDE0C4',
        'fg_dim':       '#85B7EB',
        'fg_muted':     '#4A6A8A',
        'accent':       '#378ADD',
        'accent_bright':'#5FA0E8',
        'accent_dark':  '#185FA5',
        'border':       '#1E3350',
        'card_border':  '#1A2D44',
        'note_placeholder': '#2A4060',
        'note_dot':     '#FAC775',
        'playing_bg':   '#185FA5',
        # mascot palette
        'mascot_bg':     '#091422',
        'mascot_border': '#1E5099',
        'mascot_accent': '#378ADD',
    },

    'phosphor-green': {
        'name': 'Phosphor Green',
        'dark': True,
        'window_bg':    '#070D07',
        'header_bg':    '#040904',
        'card_bg':      '#0C150C',
        'input_bg':     '#101A10',
        'hover_bg':     '#162016',
        'note_bg':      '#050C05',
        'art_bg':       '#040A04',
        'fg':           '#A8D870',
        'fg_dim':       '#70A850',
        'fg_muted':     '#3A6030',
        'accent':       '#5AC83A',
        'accent_bright':'#7AE058',
        'accent_dark':  '#2A7018',
        'border':       '#183820',
        'card_border':  '#142E18',
        'note_placeholder': '#1E3A18',
        'note_dot':     '#D4A830',
        'playing_bg':   '#204A18',
        'mascot_bg':     '#040904',
        'mascot_border': '#1E4A18',
        'mascot_accent': '#5AC83A',
    },

    'warm-amber': {
        'name': 'Warm Amber',
        'dark': True,
        'window_bg':    '#1A1208',
        'header_bg':    '#110C04',
        'card_bg':      '#221608',
        'input_bg':     '#1C1408',
        'hover_bg':     '#2A1C0C',
        'note_bg':      '#140E04',
        'art_bg':       '#100A02',
        'fg':           '#ECCF7A',
        'fg_dim':       '#C89A48',
        'fg_muted':     '#7A5820',
        'accent':       '#D08020',
        'accent_bright':'#E8A040',
        'accent_dark':  '#885010',
        'border':       '#3A2810',
        'card_border':  '#301E08',
        'note_placeholder': '#3A2010',
        'note_dot':     '#E8A040',
        'playing_bg':   '#6A3A08',
        'mascot_bg':     '#110C04',
        'mascot_border': '#503010',
        'mascot_accent': '#D08020',
    },

    'light': {
        'name': 'Daylight',
        'dark': False,
        'window_bg':    '#F2EDE4',
        'header_bg':    '#E8E2D6',
        'card_bg':      '#FDFAF5',
        'input_bg':     '#EDE8DF',
        'hover_bg':     '#E4DDD2',
        'note_bg':      '#F8F4EE',
        'art_bg':       '#DDD8D0',
        'fg':           '#1E1810',
        'fg_dim':       '#5A4E3C',
        'fg_muted':     '#8A7A68',
        'accent':       '#2060A8',
        'accent_bright':'#3A80C8',
        'accent_dark':  '#144080',
        'border':       '#C8C0B0',
        'card_border':  '#D8D0C0',
        'note_placeholder': '#B0A898',
        'note_dot':     '#C07020',
        'playing_bg':   '#BDD4EE',
        # mascot light -- warm cream body, brown border, white eyes to match reel circles
        'mascot_bg':     '#EDE8DC',
        'mascot_border': '#8A7060',
        'mascot_accent': '#2060A8',
        'mascot_eye':    '#FFFFFF',
    },
}

DEFAULT_THEME = 'technics-blue'


def get_theme(key: str) -> dict:
    return THEMES.get(key, THEMES[DEFAULT_THEME])
